app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb
app/workers/commit_monitor_handlers/commit/gemfile_checker.rb
app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb

Eventually I want to extract the github message builder class, but for now I just added in the tags themselves.  This makes it easier to find old commits for cleanup and deletion.  These tags are not visible in the UI (as you can see here: <wow_invisible />)

Added invisible HTML tags to github comments for easy detection.

---

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb

Goes with ManageIQ/manageiq#1657 and ManageIQ/guides#54
Issue #9
Example (hand edited from a PR on ManageIQ/manageiq):
---
Checked commit https://github.com/h-kataria/manageiq/commit/01e3b442bf39c0f9c0c2c907812d7f27e9a2db01 with rubocop 0.27.1
1 file checked, 5 offenses detected
**vmdb/app/helpers/application_helper.rb**
ems_infra flavor host miq_proxy miq_schedule miq_template policy ontap_file_share ontap_logical_disk
ontap_storage_system ontap_storage_volume orchestration_stack repository resource_pool scan_profile
security_group service snia_local_file_system storage storage_manager timeline)` appeared in a condition.

Changed rubocop prefix to use colored emoji for readability

---

app/workers/commit_monitor_handlers/commit/gemfile_checker.rb
config/settings.yml

* Configure the repository that GemfileChecker monitors.
* This makes it easier to test "ManageIQ/sandbox" as an example.
* Delete prior Gemfile comments before adding a new one.
* Add the "gem changes" label to the PR if it's not already applied.
* Fixes #3
cc @Fryguy 
Once this in, we can extract much of the code that is similar to the rubucop checker that detects the already existing comments.

Enhance gemfile checker

---

app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb

We don't want key/value pairs --files file1, file2, etc.
We want file1, file2, etc.
Fixes:
Executing: rubocop --files Gemfile --format json
invalid option: --files

Fix #30 haml PR to list just the files on the command line.

---

README.md

* Change the docs to indicate that
`config/settings/development.local.yml` should be used instead of
`config/settings.local.yml` so they are not available in the test environment.
Not sure about this, but I'm adding this with the thought that isolated tests should not change the world, so these settings should only be available for development. Any thoughts?

Use config/settings/development.local.yml

---

app/models/commit_monitor_branch.rb
app/models/commit_monitor_repo.rb
app/workers/commit_monitor_handlers/commit_range/gemfile_checker.rb

The gemfile checker was a commit handler, so could generate more noise than was
required for PRs that had Gemfile changes over several commits. This changes it
to a commit range handler which allows only one comment for multiple Gemfile
changes.
https://trello.com/c/ts3G5COh/11-miq-bot-gemfile-checker-should-be-a-commit-range-handler-not-commit-handler
Fixes #78 
Below screenshot shows it now doing a single comment with a range of commits:

Make gemfile checker a range handler.

---

.gitignore
README.md

* Adds a `repos` folder so it does not need to be created in development steps
* Ignores anything in the `repos` folder so things added there for development are not tracked.
* Removes the corresponding step from the README

Add a repos folder, but ignore its contents.

---

.gitignore
README.md

This gets my git status back to clean by ignoring a custom Procfile
that's just a copy of the one checked in. It can now be edited to fit
development needs without creating a dirty git state. The README has
been updated to reflect the change, and includes instructions on running
foreman with a custom Procfile.

Create a development Procfile that won't be tracked.

---

app/workers/issue_manager_worker.rb
lib/bot/issue_manager.rb
spec/workers/issue_manager_worker_spec.rb

Removes the `exit 1` that could kill the whole bot.

Cleanup IssueManager credentials check.

---

app/workers/travis_build_killer.rb

- Kill PR's as we used to, the only thing left is branch builds
- Skip running builds
- Cancel what is left as we did before

Don't kill running branch builds, it messes with coveralls

---

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb

Sometimes, rubocop will be running on a different ruby version than
the developer who opened the pull request.
This leads to very :confused: developers as rubocop could report
syntax errors such as %i (added in 2.0) if the bot is using ruby 1.9.3.
Printing the ruby version may help clarify why it's invalid syntax.
Fixes #114

Print the ruby version in rubocop comments

---

app/workers/commit_monitor.rb

2015-09-23T19:08:46Z 875 TID-mfjfo WARN: Attribute was supposed to be a Array, but was a String. -- "---\n- b912c2c82de4463ddf8a926d1ad3c04b5b726d5a\n"

Let ActiveRecord serialize the column to avoid:

---

app/workers/commit_monitor.rb

The persistent cache was causing the bot to post PR links to bugzilla tickets
when the BZ had not been referenced in any of the PR's commit messages.
This could happen when an earlier PR branch had a BZ URI in one of
the commit messages that got stored in the `@new_commits_details` cache.
In that case we would iterate through the first (BZ) branch's commits
as well as the new branch commits during processing, causing us to see the
BZ URI in the context of the new branch.

Clear out new_commits_details cache for each branch

---

app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb

https://github.com/ManageIQ/miq_tools_services/blob/cee3bd5e26fb692ee62aca5023e2b7264f017847/lib/miq_tools_services/github.rb#L40-L47
@Fryguy @bdunne Saw this when I was trying to run the bot in "read-only" github mode.  I had to manually modify this line to prevent it from writing to github.  The only other places I had to make it "read-only" were the modification methods in MiqToolsServices, which is the goal.

Use the common miq_tools_services github_api method

---

app/models/repo.rb
db/migrate/20151207193108_remove_path_from_repo.rb
db/schema.rb
spec/factories/repo.rb
spec/models/repo_spec.rb

@bdunne Please review.  I think this should go at the same time as https://github.com/ManageIQ/miq_tools_services/pull/19
Note that this depends on https://github.com/ManageIQ/miq_tools_services/pull/20 (clone support) getting released.

Force the bot to only load repos from the repos directory.

---

README.md
app/models/repo.rb

* Repo#branches= requires an array. …
* Fixes a bug from #141
```
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-  4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing': undefined method `each' for #  <Branch:0x00000005bf1ad0> (NoMethodError)
...
from /opt/miq_bot/app/models/repo.rb:20:in `create_and_clone!'
```
*  The git clone and create Repo step are now one step via #141 …
*  create_from_github! now handles creating and cloning so we pass the name and git url instead of the path to the repo.
`Repo.create_from_github!("miq-test/sandbox", git@github.com:miq-test/sandbox.git)'`

Fix #141 create_from_github!

---

app/workers/commit_monitor.rb

The statistics hash is retained through the life of one run of the
commit monitor, which can traverse 100+ branches, so all commits and
new commits for all branches is a lot of data.
We currently only care about "master" so we can compare PRs against
any new commits to "master".  Using Branch#pull_request? will allow
us to use non-master branches at some point.
Additionally, we don't ever use statistics[:all_commits] so don't
store it.

Retain only new commits for non-PR branches.

---

app/workers/commit_monitor_handlers/commit/bugzilla_pr_checker.rb

This will avoid issues like the one that happenend here https://bugzilla.redhat.com/show_bug.cgi?id=1296248 where the bot comments and sets needinfo when there was a bad rebase.

Remove comment and needinfo flag when BZ is referenced after ONDEV state

---

app/models/branch.rb

Previously we were diffing between the tips of the branches and getting too many deltas.  We should be diffing between the merge_base and the tip of the PR.
Helpful link... https://github.com/libgit2/libgit2/issues/1679

Fix rugged diffs

---

app/models/branch.rb
app/workers/pull_request_monitor/pr_branch_record.rb
lib/git_service/branch.rb
lib/git_service/diff.rb
lib/linter/rubocop.rb
spec/workers/pull_request_monitor/pr_branch_record_spec.rb

Add GitService::Branch wrapper to simplify branch methods
Add GitService::Diff wrapper to simplify walking changes
Update Linter::Rubocop to leverage the new GitService classes

Fix rugged diffs for rubocopping

---

app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb

Currently, when a rubocop linter tries to run against an unmergable PR, Rugged fails to create an index and raises `Rugged::IndexError`.  That error is raised and Sidekiq puts the job into retry.  We should not retry the job, since a rebase and push from the user should trigger a new rubocop run to be scheduled.

Don't retry to rubocop an unmergable PR

---

app/workers/commit_monitor_handlers/commit/bugzilla_pr_checker.rb

Sometimes people make PRs with bad rebases that include many commits which should not have been in the PR. This has caused the BugzillaPrChecher to comment on every BZ referenced in those commits with this new PR link.
This change will not completely solve the issue, but will at least prevent the bot from adding comments to BZs which obviously already have fixes (statuses not NEW, ASSIGNED, ON_DEV) and should not be being referenced in PR commits.
Alternative to #193 
@bdunne what do you think?

Check the bug status before making a comment

---

Gemfile
Gemfile.lock

This version fixes a bug with Pathname objects, which is required for
the bot to work correctly when cloning from GitHub.

Upgrade awesome_spawn to v1.4.1

---

app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_filename_checker.rb
app/workers/commit_monitor_handlers/commit_range/gem_changes_labeler.rb
config/settings.yml
spec/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_filename_checker_spec.rb
spec/workers/commit_monitor_handlers/commit_range/gem_changes_labeler_spec.rb

This removes the batch commenting for gem changes.  For those parties
involved, this was not a useful feature anyway, so this simplifies this
down to just labeling.
@bdunne Please review
cc @JPrause @simaishi ... just letting you know I am removing the PR comments about gemfile changes.

Extract GemChangesLabeler from DiffFilenameChecker

---

app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb
app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker.rb
spec/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker_spec.rb

This allows the bot to comment when an offender is included in a PR diff.
i.e. Someone leaves a `puts` in their code, however it can be ignored in the tools directory where it is expected.
Fixes #32

Add a diff content checker to match Strings, Symbols and Regexps

---

app/workers/pull_request_monitor/pr_branch_record.rb
spec/workers/pull_request_monitor/pr_branch_record_spec.rb

Sometimes the repo is nil, so we need a different html_url.
i.e. User creates a PR then deletes their fork

Fix "undefined method html_url for nil"

---

Procfile.tmpl
config/application.rb
lib/tasks/travis_event_listener.rake
lib/travis_event/listener.rb

Make TravisEvent::Listener a library, add a rake task to run it

Ensure 'lib' is eager loaded to avoid missing constants in workers

---

app/workers/commit_monitor_handlers/commit_range/sql_migration_labeler.rb
config/settings.yml
spec/workers/commit_monitor_handlers/commit_range/sql_migration_labeler_spec.rb

This is mostly copied from the gem changes labeler.  There is a bit of a pattern, but I'm not ready to DRY it up into a separate class until I see a 3rd one ([Rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) and all that)
@bdunne  Please review.

Add sql migration labeler

---

app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker.rb
app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_filename_checker.rb

If a PR is not mergeable, trying to look at the diff will raise a Rugged::IndexError and put the item into the retry queue

Don't put effort into unmergeable PRs

---

spec/models/repo_spec.rb

attributes are keyed by String objects, so this *actually* fixes it.

Fix specs on branches where we eliminate the last_changed_on key

---

lib/linter/rubocop.rb

This was added in https://github.com/ManageIQ/manageiq/pull/11750 so that we could avoid inheriting from a remote repo as that is not supported by code climate.
@bdunne @jrafanie please review

Add the .rubocop_base.yml file to the linter config files list

---

app/workers/commit_monitor_handlers/commit/bugzilla_commenter.rb
app/workers/commit_monitor_handlers/commit/bugzilla_pr_checker.rb

These are auto loaded by Rails and the re-require causes warnings of
redefining the BugNotFoundError therein when you load the bot.

Removed needless requires, removes warnings

---

README.md
app/models/repo.rb
spec/models/repo_spec.rb

If the git scheme is used when cloning from GitHub the
`PullRequestMonitor` will fail with a `Rugged::NetworkError`. This
change updates the README to advise using the correct url as well as
providing better defect localization.

Prevent the use of git scheme when cloning from GitHub

---

README.md

The gem_changes_labeler was changed in 01aaebfde640df98aa8e2582d6b37e3a34b7a6af

Clearer example config in README

---

app/controllers/backport_requests_controller.rb
app/views/backport_requests/index.html.erb
app/views/layouts/_navbar.html.erb
config/routes.rb
lib/backporting.rb

Using the GitHub search API, every pending backport for a target branch
name can be identified with a single API request. This change adds a new
dashboard view for backport requests per branch.
The request to GitHub when the page is viewed so there is a small chance
of bumping into rate limits. The search API has it's own rate limits
(30/minute), so it should not affect existing bot behavior and should
not be reached under normal circumstances.

Use GitHub search API to construct backport requests view

---

README.md
app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb
spec/workers/commit_monitor_handlers/branch/pr_mergeability_checker_spec.rb

Also removes the 'unmergeable' label when the PR becomes mergeable
again.
Closes #64.

Add 'unmergeable' label when a PR becomes unmergeable

---

README.md
app/models/git_hub_api/organization.rb
app/models/git_hub_api/repo.rb
app/models/github_notification_monitor.rb
spec/models/github_notification_monitor_spec.rb

Previously, we would filter against the organization members, but this
is invalid.  It just *happened* to work in the main repo, because
everyone was an assignee in the main repo, but when moving out to a
split repo, this is no longer valid.
Additionally, organization member caching was only implemented for this
purpose, so instead this is removed in favor of per-repo caching of
assignees.  Also, the org parameter to the GithubNotificationMonitor was
only there for the org member caching, so it too is removed.

Fix issue where invalid assignees were being sent

---

app/models/branch.rb
app/models/repo.rb
app/workers/concerns/branch_worker_mixin.rb
app/workers/pull_request_monitor.rb
app/workers/pull_request_monitor_handlers/merge_target_titler.rb
config/settings.yml
spec/factories/branch.rb
spec/models/branch_spec.rb
spec/models/repo_spec.rb
spec/workers/pull_request_monitor_handlers/merge_target_titler_spec.rb
spec/workers/pull_request_monitor_spec.rb

which will change a PR title to tag it with the target branch if it is
not master.
Example:
PR titled "My PR title" is created targeting branch "foo", so PR title
will be changed to "[FOO] My PR title"
Closes #174
In order to support this new type of handler, this PR adds reacting to PR changes and calling dedicated handlers.

Add PullRequestMonitorHandlers::MergeTargetTitler

---

README.md
app/models/repo.rb
spec/models/repo_spec.rb

This was added because it was assumed that SSH URLs wouldn't work, but they work fine as long as the bot account has the keys in place.

Remove and clarify the HTTPS git URL restriction

---

app/models/repo.rb
spec/models/repo_spec.rb
spec/support/miq_tools_services_helper.rb

This prevents it from running on every single call to with_git_service

Move up the ensure_prs_refs call to the creation of the repo

---

Gemfile
README.md
app/workers/commit_monitor_handlers/commit/pivotal_pr_checker.rb
config/initializers/miq_tools_services_initializer.rb
config/settings.yml
lib/pivotal_service.rb
lib/service_mixin.rb
spec/lib/pivotal_service_spec.rb

Accepted URL formats are:
- `https://www.pivotaltracker.com/story/show/<story_id>`
- `https://pivotaltracker.com/story/show/<story_id>`
- `https://www.pivotaltracker.com/n/projects/1953721/stories/<story_id>`
- `https://pivotaltracker.com/n/projects/1953721/stories/<story_id>`
Part of https://github.com/ManageIQ/miq_bot/issues/241
@bdunne Please review

Add PrivotalPrChecker to look for Pivotal stories in commits

---

Gemfile

haml-lint was bumped to support the latest rubocop, so this PR bumps both to the latest.

Bump rubocop and haml-lint

---

lib/github_usage_tracker.rb

When there's no github requests in a 60 second timeframe, no data is
added to Influx. Therefore, when aggregating data for display use
the previous datapoints instead of null for that interval.
Fixes:

Use previous datapoints in usage aggregation query

---

db/migrate/20170127173128_fix_limit_in_schema.rb
db/schema.rb

The bot is currently getting changes in its git stage because the db was
created from a previous era where Rails put limits in its columns
without you specifying. This migration is a no op in the bot's
perspectice but adds these limits for development environments so the
schema is exactly the same as what the bot currently uses.

Fix limit diff from bot db

---

lib/miq_bot.rb

Due to minigit changing GIT_DIR, the bot was recording SHAs from random
repos.
In console:
```ruby
> `git rev-parse --short --verify HEAD`
fatal: Not a git repository: 'asdf'
=> ""
> MiqBot.current_bot_sha
=> "cf4e9fe"
> `git rev-parse --short --verify HEAD`
fatal: Not a git repository: 'asdf'
=> ""
```

Fix incorrect SHA recording

---

app/models/git_hub_api.rb
app/models/github_notification_monitor.rb
config/initializers/octokit.rb
lib/github_service/response/ratelimit_logger.rb
lib/github_usage_tracker.rb
spec/lib/github_usage_tracker_spec.rb

* Request URIs are now recorded, so we can see and quantify painpoints in our API usage
* Begins the shift to pure Octokit by configuring outside of `GithubApi`
* Reuses RateLimitLogger middleware for all Octokit requests instead of doing it's own thing

Measure Github request URIs

---

config/initializers/octokit.rb

Apparently order matters, and we're losing some request recording because it's not wrapping other things octokit does. Adapter should always be last, as well.

Fix Faraday middleware order

---

lib/github_usage_tracker.rb

Hooks in to the backtrace on recording Github API requests and tries to find a worker to blame for this request being made.

Record workers from backtrace on Github requests

---

Gemfile

There should be no changes on our end to be compatible with this version.
For more, see https://github.com/octokit/octokit.rb#upgrading-guide

Upgrade Octokit to 4.6.x

---

Gemfile
config/initializers/octokit.rb

This gem adds a Faraday middleware that caches HTTP responses by checking
expiration and validation of the stored responses. It could be completely worthless given our requests/responses, or it could be a super easy win to immediately lower our API usage and get under the rate limit.
It uses the following headers to make caching decisions:
* Cache-Control
* Age
* Last-Modified
* ETag
* Expires
We might want to consider utilizing Redis for our application cache, but
I've left the default FileStore cache to use for now. Both FileStore and
Redis work across processes so workers should share the same cache
regardless.
I don't know of a very good way to test this other that just shipping it
and watching closely, which is honestly what I recommend we do. Monitor
the logs and watch hit/misses …

Use Faraday HTTP caching

---

lib/github_service/response/ratelimit_logger.rb
lib/github_usage_tracker.rb

Ruby doesn't really do a lot with nanosecond precision, as it kind of pushes the limitations of the language. However, this change should squeeze out the most accurate possible* measurement of
nanoseconds I can come up with.
This change seems to often detect two of the three requests in the GithubNotificationMonitor that get called in rapid succession, instead of the one that usually gets detected in ms precision.
*Note that according to Ruby documentation, #nsec is actually a more accurate measurement of nanoseconds, but I don't see how one actually uses that to record the full timestamp as it's only the fractional bit of seconds. For more, see http://ruby-doc.org/core-2.4.0/Time.html#method-i-nsec

Squeeze out near nanosecond precision

---

lib/github_service/response/ratelimit_logger.rb
lib/github_usage_tracker.rb

Reverts ManageIQ/miq_bot#284
Oops®
This doesn't appear to work as intended, metrics are broken.
```
InfluxDB::Error: {"error":"unable to parse 'github_api_request,bot_version=v0.0.33-6-ga596e04 requests_remaining=1i,uri=\"TEST\" 2017-02-03T11:45:52.784831000-05:00': bad timestamp"}
```

Revert "Squeeze out near nanosecond precision"

---

config/initializers/octokit.rb

We're seeing some odd behavior with the bot responding again after doing
so earlier; since we got so much from the optimizations let's try
without caching and see where that leaves us.
As long as it's under the rate limit, we're moving on to webhooks
eventually anyway.

Disable caching for now

---

app/models/git_hub_api/issue.rb
app/workers/pull_request_monitor_handlers/wip_labeler.rb
config/settings.yml
lib/github_service.rb
spec/models/git_hub_api/issue_spec.rb
spec/workers/pull_request_monitor_handlers/wip_labeler_spec.rb

This is the first part of supporting automatic WIP labeling and handles
a user changing the title to have [WIP].  Not yet handled is when a user
removes [WIP], nor if they manually add the label with an miq-bot command
Issue #34
~~Built on top of #219 since that one has the basis for PR handlers.  See only the last commit.~~ #219 is merged and this has been rebased.
@bdunne Please review

Add PullRequestMonitorHandlers::WipLabeler

---

.gitignore

Followup to #299
Makes it easy to set ruby version locally to whatever you want without gitignoring yourself, and more importantly serves as an indicator that we *intend* that we're not locking the Ruby version.

Ignore .ruby_version

---

Gemfile
Gemfile.lock
app/models/branch.rb
app/models/repo.rb
app/views/main/_commit_monitor.html.erb
app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb
app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb
app/workers/commit_monitor_handlers/commit/bugzilla_commenter.rb
app/workers/commit_monitor_handlers/commit_range/gem_changes_labeler.rb
app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
app/workers/commit_monitor_handlers/commit_range/sql_migration_labeler.rb
app/workers/concerns/branch_worker_mixin.rb
app/workers/pull_request_monitor.rb
app/workers/pull_request_monitor_handlers/merge_target_titler.rb
app/workers/pull_request_monitor_handlers/wip_labeler.rb
lib/backporting.rb
lib/new_github_service.rb
spec/spec_helper.rb
spec/support/services_helper.rb
spec/workers/commit_monitor_handlers/branch/pr_mergeability_checker_spec.rb
spec/workers/commit_monitor_handlers/commit_range/gem_changes_labeler_spec.rb
spec/workers/commit_monitor_handlers/commit_range/sql_migration_labeler_spec.rb
spec/workers/pull_request_monitor_handlers/merge_target_titler_spec.rb
spec/workers/pull_request_monitor_handlers/wip_labeler_spec.rb
spec/workers/pull_request_monitor_spec.rb

Introduces a simpler, betterer Github service class implemented with Octokit.
It uses a singleton pattern just like Octokit and most other such gems, and opts out of the service 'call' pattern we've been doing, as discussed at length. Rewriting sections to use this wrapper was stupid easy and straightfoward. Core functionality from the original GithubService was added (but renamed, to feel more natural with Octokit's like-methods).
I also found it easy to use over my previous OctokitWrappers implementation, so I'll be removing that one in favor of this, as well as removing the current GithubService and renaming this one, in a future PR.
Although low priority, I suggest that we do the other services in this pattern except for GitService. MiniGit is a special little snowflake and the thread …

New GithubService singleton wrapper

---

lib/git_service/branch.rb
lib/linter/base.rb

@chrisarcand or @bdunne Please review.
This is a minor refactor, which I need for enable_disable support, but could be pulled out into its own PR.  Basically, I can't see why a caller would ever want the raw Rugged::Blob object versus just its content.  So, this changes the interface to just get the content.  The only current caller also just wants the content.

Replace blob getter with a content getter

---

config/application.rb
lib/console_methods.rb

To my surprise, Sidekiq doesn't provide a way to process a queue in the console.
That's sort of annoying for testing stuff locally, because it takes forever to let the application process things fully. For example, to test a pull request handler:
* Start up all processes with foreman
* Push a commit to the test repo
* Wait for the pull request monitor job to enqueue and process (5 minutes, potentially)
* Wait for the github notification monitor to enqueue and process (5 minutes, potentially)
* Wait for workers enqueued from the GHNM to process (???)
Yuge waste of time. I sit staring at the screen waiting for the bot to act alive or get distracted by Twitter et al waiting, etc.
On top of that, because of the separate Sidekiq processes, debugging is sort of annoying because you don't have …

Add dev helper method for sidekiq processing

---

lib/github_service/commands/add_label.rb
lib/github_service/commands/assign.rb
lib/github_service/commands/base.rb
lib/github_service/commands/remove_label.rb
lib/github_service/commands/set_milestone.rb
lib/github_service/issue.rb

This makes it possible to easy restrict a command to a subset of users. The only type of restriction currently supported is organization, which restricts use of those commands to members of the issue's organization.
**REQUIRES #328, merge that first for a sane diff**
Enables #311, once the issue mover is properly rebased with the new command structure.

Add command restrictions

---

README.md
lib/github_service/commands/move_issue.rb
lib/github_service/issue.rb

**REQUIRES #329; merge that first**
Closes #258
@Fryguy Please review
cc/ @blomquisg 
Move success (original issue):
Move success (new issue):
Trying to move a pull request:
Trying to move an issue and you're not part of the org:
With several qualifications, errors are combined to human readable sentences so people don't hit their head against the wall over and over. For example, trying to move a pull request AND trying to specify a repo outside of the issue's organization:

Issue mover

---

lib/github_service/command_dispatcher.rb
lib/github_service/commands/add_label.rb
lib/github_service/commands/assign.rb
lib/github_service/commands/base.rb
lib/github_service/commands/close_issue.rb
lib/github_service/commands/remove_label.rb
lib/github_service/commands/set_milestone.rb
lib/github_service/issue.rb

**REQUIRES #329; merge that first**
Closes #191 
Adds a command for organization members to close issues without commit access.
* Some dispatcher parsing had to be reworked because the previous implementation didn't allow for commands with no parameters.
* If the issue is a pull request, only the author of the pull request or a committer (manually) can close it. I don't like the idea of just anyone being able to close the door on contributions from other contributors.

Add close_issue command

---

lib/github_service.rb

People sometimes need to retroactively add a milestone to a PR that was
merged in the previous sprint. Without this option, you can only assign
to the current open sprint.
See https://github.com/ManageIQ/manageiq-gems-pending/pull/77

Pull old milestones, too

---

app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb

While trying to generate the diff on an unmergeable PR it will raise.
If this is not rescued, the job will be requeued and continue to fail

Rescue UnmergeableError

---

app/workers/schedulers/stale_issue_marker.rb
app/workers/stale_issue_marker.rb
config/settings.yml
lib/github_service.rb
spec/workers/stale_issue_marker_spec.rb

Inspired by rails-bot (which in this case is nothing more than [a manual script](https://github.com/rafaelfranca/rails-tools/blob/master/bin/mark_stale_issues) run by Rafael every few months), this worker takes out the trash over the weekend and helps clean up old issues and pull requests in every enabled repo.
* A pull request or issue that hasn't been updated (commented on, whatever) in the last **6 months** is considered stale.
* Stale *issues* are marked with the 'stale' label and commented on.
* Stale *pull requests* are closed and commented on. 
* As with rails-bot, issues/pull requests can be 'pinned' - that is, if the label 'pinned' (or any other label that we deem worthy) is present on the issue, it will not be marked as stale or closed even if it's extremely old. This is useful …

Stale issue/PR marker

---

db/migrate/20170127173128_fix_limit_in_schema.rb

Trying to revert this migration results in this error:
```
== 20170127173128 FixLimitInSchema: reverting =================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
ActiveRecord::IrreversibleMigration/home/tim/src/miq_bot/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/migration/comman
d_recorder.rb:65:in `inverse_of'
```
~~Changing it to an `up` and doing nothing on the `down` should be fine.~~
Edit: We need to tell it explicitly how to undo the change by setting
`:limit => nil`.
@miq-bot assign @chrisarcand

Fix irreverible migration

---

app/workers/schedulers/stale_issue_marker.rb

I've realized that having a ton of notifications at the beginning of a relaxing weekend is actually sort of stressful even if it's just the bot marking stuff. Part of that is being disciplined enough to ignore your notifications for the weekend, but there's no reason we can't alleviate the perceived pain.
This will activate at midnight (ET) on Sunday night, really, so people will be notified of stale stuff they might want to go over that week on Monday morning.

Change stale issue marker to Mondays

---

.travis.yml
app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
lib/linter/base.rb
lib/linter/yaml.rb
spec/lib/linter/yaml_spec.rb
spec/support/rubocop_spec_helper.rb
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb

Warning: requires a `yamllint` executable on the path of the bot. It's available in dnf/apt/etc... but I'd recommend using the most recent version available via `pip`.
See https://github.com/miq-test/sandbox/pull/42#issuecomment-332899807 for an example of output.
@miq-bot assign @Fryguy

Add a YAML linter

---

app/models/branch.rb
app/workers/commit_monitor_handlers/branch/code_analyzer.rb
app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
app/workers/concerns/code_analysis_mixin.rb
app/workers/schedulers/code_analyzer.rb
config/settings.yml
db/migrate/20171006050814_add_linter_offense_count_to_branch.rb
db/schema.rb
lib/git_service/branch.rb
lib/linter/base.rb

I hope this will be added to the statistics on the Sprint review. Here we can have an overall metric on how many linter offenses there are in each repo.  Eventually I'd like to keep historical data, but on this first pass, we can get daily numbers saved on the branch record.

Implement a daily Code analyzer

---

lib/github_notification_monitor.rb
lib/github_service/notification.rb

- Don't blow up when a comment body is nil
- Example: https://github.com/ManageIQ/manageiq-appliance/pull/147
- Enhance `issue_number` matching to verify that everything after `/` is an integer
- Only process notifications that have an `issue_number`

New comment issues

---

app/models/branch.rb
app/models/repo.rb
app/workers/commit_monitor.rb
app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker.rb
app/workers/commit_monitor_handlers/commit/pivotal_pr_checker.rb
app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb
app/workers/concerns/branch_worker_mixin.rb
app/workers/concerns/sidekiq_worker_mixin.rb
app/workers/github_notification_monitor_worker.rb
app/workers/pull_request_monitor.rb
app/workers/pull_request_monitor_handlers/merge_target_titler.rb
app/workers/pull_request_monitor_handlers/wip_labeler.rb
app/workers/schedulers/code_analyzer.rb
app/workers/schedulers/stale_issue_marker.rb
app/workers/travis_build_killer.rb
config/settings.yml
config/settings/test.yml
spec/models/branch_spec.rb
spec/models/repo_spec.rb
spec/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker_spec.rb
spec/workers/commit_monitor_handlers/commit_range/path_based_labeler_spec.rb
spec/workers/concerns/branch_worker_mixin_spec.rb
spec/workers/pull_request_monitor_spec.rb

This PRs standardizes on repo names in the settings.yml for all workers and supports them in any worker.
The way the settings.yml will work is to specify either included_repos, excluded_repos, or nothing.
```yaml
worker1:  # Will run in all repos
worker2:  # Will only run in the specified repos
included_repos:
- "org1/repo1"
- "org2/repo12"
worker3:  # Will run in all repos except the specified repos
excluded_repos:
- "org1/repo1"
- "org2/repo12"
worker4:  # Will raise an exception, since you should not specify both
included_repos:
- "org1/repo1"
excluded_repos:
- "org2/repo12"
worker5:  # Effectively disables the worker
included_repos: []
```
TODO:
- Support enable/disable for specific linters. (deferring to a separate PR)
- Support yaml references to avoid a lot of copy/paste in the …

Standardize on enable/disable of repos across all workers

---

app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
app/workers/concerns/code_analysis_mixin.rb

(No linters enabled for a branch)

Prevent errors from empty linter results

---

app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb

Since it now uses rugged to check mergeability and does not hold a lock on git, it is a fast operation and can be moved to the faster queue.

Change PrMergeabilityChecker queue as it's no longer a glacial operation

---

lib/bugzilla_service.rb
spec/lib/bugzilla_service_spec.rb

The tests did not catch this originally because they were not real-world
examples where git commit messages are used, and thus the message itself
is indented 4 spaces.  Regular URLs happened to work because the regex
has a \s* immediately after the optional resolution string.

Fix issue where BZ URLs prefixed with a resolution were not detected

---

lib/git_service/branch.rb
lib/linter/base.rb

We want the regular files from the tip of the branch, but we want the config files to be merged before running.

Merge rubocop config files for linting purposes

---

app/workers/commit_monitor.rb
lib/git_service/branch.rb
lib/git_service/commit.rb
lib/git_service/diff.rb

We no longer need to lock a repo while running the commit monitor.  Once the fetch is done, everything can be pulled from rugged.  This will unlock future performance improvements like processing multiple repos (and even branches) at the same time.
@Fryguy We need to do some testing before deploying, but everything was working for me in rails console.

Reduce callers to git_service

---

app/models/branch.rb
app/models/repo.rb
app/workers/commit_monitor_handlers/commit_range/branch_mergeability_checker.rb
app/workers/pr_mergeability_checker.rb
spec/factories/branch.rb
spec/models/branch_spec.rb
spec/models/repo_spec.rb
spec/workers/commit_monitor_handlers/commit_range/branch_mergeability_checker_spec.rb
spec/workers/pr_mergeability_checker_spec.rb

Instead of doing something "special" for regular branches in the commit
monitor and doing "branch" handlers in a special way, instead create a
BranchMergeabilityChecker which monitors regular branches for changes
and the queues up individual PrMergeabilityChecker runs for each PR that
is targeting the branch in question.

Change PrMergeabilityChecker to be queued by BranchMergeabilityChecker.

---

Gemfile
Gemfile.lock
README.md
lib/github_notification_monitor.rb
lib/github_service/commands/add_reviewer.rb
lib/github_service/commands/base.rb
lib/github_service/issue.rb
spec/lib/github_service/commands/add_reviewer_spec.rb
spec/lib/github_service/commands/review_spec.rb

ManageIQ Bot will support a new command which provides a "request for pull request review" functionality. This feature required to update Octokit due to [`request_pull_request_review`](https://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method) method missing. This command works on the same basis as the [`assign`](https://github.com/ManageIQ/miq_bot) command but it is supported only for pull requests.
Example: `@miq-bot review @europ`
**NOTE**: Command with multiple reviewers are not supported (assign does not support this feature too).
\cc @skateman 
\cc @romanblanco

Review request command

---

README.md
lib/github_notification_monitor.rb
lib/github_service/commands/remove_reviewer.rb
lib/github_service/issue.rb
spec/lib/github_service/commands/remove_reviewer_spec.rb

<br>
ManageIQ Bot will support a new command `remove_reviewer`. This command provides a "remove request for pull request review" functionality. The usage of this command requires to meet a condition - the user must be a requested reviewer in the pull request. If condition is met, the command perform an action which removes the user from the reviewer list in the pull request.  This command is the opposite of `add_reviewer` which is described in https://github.com/ManageIQ/miq_bot/pull/408
Example: `@miq-bot remove_reviewer @europ`
**NOTE**: Command with multiple reviewers is not supported
\cc @skateman 
\cc @romanblanco

Remove a request for pull request review command

---

lib/github_service/commands/remove_reviewer.rb

The exception handling in the https://github.com/ManageIQ/miq_bot/pull/416 was replaced with a temporary solution until merge of https://github.com/octokit/octokit.rb/pull/990.
\cc
@Fryguy 
@skateman

Remove_reviewer implemented without dependence

---

app/workers/pr_mergeability_checker.rb
spec/workers/pr_mergeability_checker_spec.rb

Except of label deletion the bot also deletes the comments describing unmergeable status of the pull request.
\cc
@skateman 
@romanblanco

Remove unnecessary unmergeable comments

---

README.md

GitHub pull requests are also checked with yamllint [here](https://github.com/ManageIQ/miq_bot/blob/master/app/workers/concerns/code_analysis_mixin.rb#L26). Yamllint is also a miq_bot's dependency defined in the [setup](https://github.com/ManageIQ/miq_bot#setup).

Added missing linter into README.md

---

Gemfile
Gemfile.lock
app/workers/commit_monitor_handlers/commit_range/bugzilla_pr_checker.rb
config/initializers/services_initializer.rb
lib/bugzilla_service.rb
spec/lib/bugzilla_service_spec.rb

Replaced with some inline http calls via Faraday.  Uses the REST API, since the XMLRPC API has been deprecated and removed in BZ 5.0, and the bits needed for this app are small enough to not warrant trying to get all of `active_bugzilla` up to to code with the new API format.
Mostly marked [WIP] at this point because I haven't tested the PUT/POST actions.
Links
-----
* API docs specific to RedHat Bugzilla:
- https://bugzilla.redhat.com/docs/en/html/api/core/v1/general.html (for authentication)
- https://bugzilla.redhat.com/docs/en/html/api/core/v1/bug.html (GET/PUT bugs)
- https://bugzilla.redhat.com/docs/en/html/api/core/v1/comment.html (GET/CREATE comments)
QA
--
Just a command line way to test the `GET` requests in the `BugzillaService`
1. Setup your bugzilla settings in …

Remove active_bugzilla

---

lib/linter/base.rb

- No other linters run
- The job gets requeued (and usually will never succeed)
Here's the retry queue:

Raising causes problems

---

README.md
lib/github_notification_monitor.rb
lib/github_service/commands/unassign.rb
spec/lib/github_service/commands/unassign_spec.rb

A new command was added by which can be users unassigned from an issue or pull request. The command supports multiple users in a comma separated notation. The specified users must be in the list of assignees.
\cc
@skateman
@Fryguy

unassign command

---

README.md
lib/github_service/commands/add_reviewer.rb
lib/github_service/issue.rb
spec/lib/github_service/commands/add_reviewer_spec.rb

The commands add_reviewer or add_reviewers supports pull request review request for multiple users.
Command has a restriction for the users - they must be **separated by a comma**. 
The bot is able to perform these following commands:
`@bot add_reviewer @user`
`@bot add_reviewers @user`
`@bot add_reviewer @user1, @user2`
`@bot add_reviewers @user1, @user2`
`@bot add_reviewers @user1         ,@user2`
`@bot add_reviewers @user1,         @user2`
`@bot add_reviewers @user1         ,         @user2`
<br>
The separation between specified users is defined by regular expression `/\s*,\s*/` - the comma is required and the white spaces are optional. 
<br>
\cc @skateman

Command add_reviewer supports multiple users

---

lib/git_service/branch.rb
lib/linter/base.rb

Addresses: https://github.com/ManageIQ/miq_bot/issues/445
When checking out the contents of the file to run linters against use Rugged, the content was just copied to a new file without taking into account the permissions that are set in the repository object.
This fix now performs a check and creates a file matching the permissions found in the repo being linted.
@miq-bot assign @bdunne

[Linter::Base] Fix rubucop file permission check

---

lib/github_service/commands/add_label.rb
spec/lib/github_service/commands/add_label_spec.rb

Adds `DidYouMean` support to `GithubService::Commands::AddLabel`, which will auto correct invalid labels, or at the very least provide options for incorrect labels.
This PR does slightly change the format of "incorrect label" issue comments.
Links
-----
- "Inspiration":  https://gitter.im/ManageIQ/manageiq/core?at=5e29e4591a1c2739e3e8b85f

MiqBot AutoCorrect for AddLabel

---

app/workers/schedulers/stale_issue_marker.rb
app/workers/stale_issue_marker.rb
lib/github_service.rb
spec/workers/stale_issue_marker_spec.rb

This is a pretty large refactoring of the StaleIssueMarker, but makes use of the `search_issues` api to reduce the number of API calls required to run this worker.
As a side effect, it also simplifies each of the methods in the class so they are a bit easier to digest.
Links
-----
* Github `/search/issues` endpoint docs: https://developer.github.com/v3/search/#search-issues-and-pull-requests
* Original implementation:  https://github.com/ManageIQ/miq_bot/pull/331
The original implementation PR includes some design context that I think is worth being aware of when reviewing.

[StaleIssueMarker] Use GithubService.search_issues

---

lib/github_service/commands/add_label.rb
lib/github_service/commands/remove_label.rb
spec/lib/github_service/commands/add_label_spec.rb
spec/lib/github_service/commands/remove_label_spec.rb

Starting with the Jansa release, we are changing the backport process to require code changes that are requesting a backport submit the `jansa/yes?` first to get approval from the triage team.  This means that setting the `jansa/yes` label (and similar labels from this release forward) will not be allowed.
For the purposes of the bot, this means that any labels that have been assigned a `*/yes` label (only `jansa/yes` for now), will be automatically converted to `jansa/yes?`.
Also, removing any of the `*/yes` and `*/no` labels is no longer possible via the bot, and the bot will respond with a warning if removing any of the `UNREMOVABLE` labels is attempted.
Links
-----
Fixes #475

add_label/remove_label:  Prevent non-triage team assignment/removal

---

Gemfile
Gemfile.lock
config/application.rb
lib/github_service/commands/add_label.rb
lib/github_service/commands/remove_label.rb
lib/github_service/concerns/is_team_member.rb
spec/lib/github_service/commands/add_label_spec.rb
spec/lib/github_service/commands/remove_label_spec.rb
spec/spec_helper.rb
spec/support/github_service_helper.rb

Adds support for the triage team to add any labels.
Adds a concern `IsTeamMember` to handle shared code across `AddLabel` and `RemoveLabel`.
Triage team name is configurable in the settings.
Follow up from #479
**NOTE**:  I am re-using the `github_service_helper.rb` that I introduced in #454 (and also used in #481 as well), and I expect when one of those are merged, I will have to deal with the merge conflicts in the other branches.  It is an isolated commit, so rebasing it should be simple enough.

[AddLabel/RemoveLabel] Allow triage team to add all labels

---

config/settings.yml
config/settings/test.yml
lib/github_service/commands/add_label.rb
lib/github_service/commands/remove_label.rb

These values really belong to the ManageIQ organization and the bot is intended to be reusable by people in other organizations.  Prefer settings for these types of values rather than hard-coded constants.
cc @NickLaMuro

Move unassignable and unremovable labels from constants to settings

---

app/workers/stale_issue_marker.rb
lib/github_service/issue.rb
spec/workers/stale_issue_marker_spec.rb

There are a lot of changes here, and the commits go into greater detail, but at a high level:
- Bumps marking as `stale` to 3 months
- Auto closes pull requests that are `stale` and `unmergeable`
- Handles Pull Requests and Issues in the same manner
- When a `verified` issue becomes `stale`, remove `verified` and mark as `requires triage`
- Misc refactorings and changes to support the above
Notes
-----
- The `requires triage` label was just a label name I picked, but can be changed to whatever
- (when the label name is decided on, that will need to be set for all repos)
- Some code was moved around to be put in `GithubService::Issue` instead of in this class.  Mostly for readability, but I could see how it might be considered a controversial change.
- The copy for marking stale and …

[StaleIssueMarker] Better triage workflow

---

app/workers/commit_monitor_handlers/commit_range/github_pr_commenter.rb
app/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker.rb
lib/github_service.rb
spec/lib/github_service_spec.rb
spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker_spec.rb

Adds `GithubService.username_lookup` and a batch worker (`CommitMessageUsernameChecker`) to look through commit messages for any potential usernames, and warns on valid matches.
Implementation Details
----------------------
This PR takes a few steps to avoid the concerns in the original issue ( #414 ), while still addressing the concerns from this comment:
> "People may want to put the @foo in code blocks though, which should be acceptable. Whatever detection we use should allow that."
> - https://github.com/ManageIQ/miq_bot/issues/414#issuecomment-375085251
1. The `GithubService.username_lookup` will attempt to avoid using an API call by first checking against the non-api user endpoint.  If a 404 is returned, we set the value for the username key in the `username_lookup_cache` to `nil`. …

Add CommitMetadataChecker

---

db/migrate/20140115031432_create_commit_monitor_repos.rb
db/migrate/20140116232751_create_commit_monitor_branches.rb
db/migrate/20140117055336_add_pull_request_to_commit_monitor_branch.rb
db/migrate/20140117063400_add_upstream_user_to_commit_monitor_repo.rb
db/migrate/20140128174930_replace_timestamps_with_last_checked_on_and_last_changed_on_for_commit_monitor_branches.rb
db/migrate/20140214211340_add_commits_list_to_commit_monitor_branches.rb
db/migrate/20140215060546_add_mergeable_to_commit_monitor_branch.rb
db/migrate/20150730043503_create_batch_tables.rb
db/migrate/20150806034945_add_on_complete_class_and_args_to_batch_jobs.rb
db/migrate/20150814183817_rename_commit_monitor_repos_to_repos.rb
db/migrate/20150814183834_rename_commit_monitor_branches_to_branches.rb
db/migrate/20150814191457_rename_branches_foreign_key.rb
db/migrate/20150814233450_add_state_to_batch_jobs.rb
db/migrate/20150827194533_collapse_repo_upstream_user_into_name.rb
db/migrate/20151204171252_update_branch_name_for_pr_branches.rb
db/migrate/20151207193108_remove_path_from_repo.rb
db/migrate/20160119143158_add_merge_head_to_branch.rb
db/migrate/20160713200646_add_pr_title_to_branch.rb
db/migrate/20170127173128_fix_limit_in_schema.rb
db/migrate/20171006050814_add_linter_offense_count_to_branch.rb
db/schema.rb

Use 4.2 for all of the migrations, since they were all done prior to the upgrade from 4.2 -> 5.2 and '4.2' is the lowest possible value available:
```
ArgumentError:  Unknown migration version "4.0"; expected one of "4.2", "5.0", "5.1", "5.2"
```
'4.2' is the closest option that makes sense.
Links
-----
- Rails 5.2 upgrade PR:  https://github.com/ManageIQ/miq_bot/pull/466
Testing
-------
This doesn't seem to be show via CI since it probably (too lazy to check) does a `rake db:schema:load`, so doing the following:
```console
$ RAILS_ENV=development bundle exec rake db:environment:set db:drop db:create db:migrate
```
Should work with this patch in place.
Fixes #489

Fix CreateBatchTables migration

---

app/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker.rb
spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker_spec.rb

Includes better handling of variables to avoid the following better:
- Check if the `@` is preceded by whitespace or a new line (valid user)
- Don't allow trailing periods (not a user)
The trailing periods was a mistake, and was meant to be the inverse where things like this:
- `@user.name`
- `foo@example.com`
so those wouldn't get flagged by the bot.  Some examples in the specs were updated to address this cases better.
Address issue brought up in `gitter`:  https://gitter.im/ManageIQ/miq_bot?at=5e83b90b57d801084bd4935a
Example "bad" output:
---------------------
> `060b7af`
> 
> - [ ] :grey_exclamation: - Username `@redhat` detected in commit message. Consider removing.
> - [ ] :grey_exclamation: - Username `@redhat` detected in commit message. Consider removing.
> 
> `17137a6`
> 
> - [ …

[CommitMetadataChecker] Ignore emails

---

app/workers/commit_monitor.rb
lib/git_service/commit.rb

This is a followup to the changes from https://github.com/ManageIQ/miq_bot/pull/493 which ensure that we are only parsing the commit "message", and not the contents of the committer email, author email, etc.
A bit of a discussion on this can be found here:
https://gitter.im/ManageIQ/miq_bot?at=5e83d09b74c36c7bc678ff13
The PR itself is mostly a exercising in refactoring, and currently only the last two commits changes anything for the `CommitMonitor` and nested handler workers from that.
Notes on Usage of `new_commits_details`
---------------------------------------
It was brought up as a concern (by myself), that `new_commits_details` is potentially used by other handlers.  This is not the case, so this change is safe to make, but for background:
The two other …

[CommitMonitor] Send commit .details_hash instead of .full_message

---

Gemfile
Gemfile.lock

I tested this locally via `rails s`, and ran the tests with `rake`.  I'm not sure what else can prove whether we used it or not?
My main motivation is I can't seem to build libv8 at all in either Ruby 2.5 or 2.6, and if we don't need it, why not kill it?
@NickLaMuro @bdunne Please review.

Remove therubyracer gem as it's not used

---

.gitignore
db/seeds.rb

Allows for specifying a local file for seeding a database based on custom records.
Since development for this repository requires user specific repos to be created for testing, this can allow a DB reset less painfully.
**Note**:  This is also just me cleaning up some local changes I had that I figured might be worth sharing.  Feel free to close if you don't think it is useful.

Add db/seeds.local.rb support

---

Gemfile
Gemfile.lock
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_haml_file_using_haml-lint/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_lines_not_in_the_diff/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_generating_multiple_comments/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_no_offenses/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_offenses/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_without_column_numbers_and_cop_names/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_void_warnings_in_spec_files/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb

Requires `.rubocop_base.yml` changes found here:  https://github.com/ManageIQ/guides/pull/421
Further info and rational on the changes to the `.rubocop.yml` can be found in the commits for that repo.
Links
-----
- Partially addresses https://github.com/ManageIQ/miq_bot/issues/496
- Required merge in guides repo:  https://github.com/ManageIQ/guides/pull/421

Upgrade rubocop to v0.82.0 and haml_lint to v0.35.0

---

.gitignore
.travis.yml
Vagrantfile
config/database.vagrant.yml

`ruby-install` was originally picked for the `Vagrantfile` to match what was in the `.travis.yml`, and `dnf` only had 2.5.7 available.  But based on output from the bot in production:
> Checked commit NickLaMuro@b68ddde with ruby 2.5.7 ...
>
> Ref: https://github.com/ManageIQ/miq_bot/pull/497#issuecomment-624154539
We are using 2.5.7 there as well, so switching to use a `dnf` install to speed up the the over all build time of the box.
Also updating the `.travis.yml` to use 2.5.7 as well.

Upgrade ruby in .travis.yml and Vagrantfile

---

app/workers/stale_issue_marker.rb
spec/workers/stale_issue_marker_spec.rb

`updated:<` should be the keyword used, not `update:<`, as shown by the difference in these two searches:
**Returns no records**
https://github.com/search?q=org%3AManageIQ+is%3Aopen+archived%3Afalse+update%3A%3C2020-03-01+-label%3Apinned&type=Issues
**Returns (a bunch of) records**
https://github.com/search?q=org%3AManageIQ+is%3Aopen+archived%3Afalse+updated%3A%3C2020-03-01+-label%3Apinned&type=Issues

[stale_issue_marker.rb] Fix 'updated' search

---

app/workers/stale_issue_marker.rb
spec/workers/stale_issue_marker_spec.rb

Since it works for both PRs and issues.
Also fixes:
- A typo: `s/traige/triage/`
- Logging inconsistency:  Now using `issue.type` to denote the difference between closing an issue and a PR in the logs

Use .close_issue instead of .close_pull_request

---

Gemfile
Gemfile.lock
app/models/repo.rb
lib/git_service/credentials.rb
lib/git_service/repo.rb

This PR does a bunch of things to try and allow `.git_fetch` to work from `Rugged`:
- Moves logic for `Rugged` based `.git_fetch` into `GitService::Repo`
- Adds a `GitService::Credentials` in charge of finding credentials for a given remote/user
- Adds logic in `GitService::Credentials` to allow configuration of keys by host ~~(similar to `~/.ssh/config`)~~ using `~/.ssh/config` via the `net-ssh` gem
- Uses new `.git_fetch` and credential finding in `Repo` model
- Initializes git credentials (if configured) on Rails boot
Example config
---------------
~~This is what I am using for my ssh configuration for in my `config/settings/development.local.yml`:~~
**NOT NEEDED/USED.  Use example `~/.ssh/config` below instead:**
```yaml
git_service_hostname_ssh_config:
'*':
username: git
privatekey: …
```

GitService::Repo.git_fetch (and friends)

---

.rubocop.yml
Gemfile
Gemfile.lock

Switch to using manageiq-style for linting dependencies

---

Dockerfile

- Switch to using master code base
- Install `libssh2-devel` for rugged SSH fetch

Fixes for running from master

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

This avoids each auto-generated PR to have the identical name of `[BOT] Cross repo test run`
Follow-up to https://github.com/ManageIQ/miq_bot/pull/454

For cross-repo-test, make PR Name more specific

---

README.md
lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

Allow for users to specify groups of repositories with a simple `/group-name` directive.
These groups can be defined dynamically in manageiq-release config as yaml files.
Example: `@miq-bot cross_repo_tests /providers including manageiq#1234`
TODO

Process repository groups in cross-repo-tests command

---

Dockerfile

- Exclude RHEL 8.3 packages that conflict with CentOS 8.2 (Based on https://github.com/ManageIQ/manageiq-pods/pull/648)
- Skip filesystem RPM for now, there's an issue installing the new one (https://access.redhat.com/solutions/2381811)

Fix container build issues

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

We were testing that "200" != 200 and returning that we failed to fetch the repo sets yaml file, and .flat_map { {}["all"] } was resulting in the expanded repo groups being [nil]

Fix testing Net::HTTP response code

---

README.md
lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

Example (assuming the PR in questions is `manageiq#1234`)
`@miq-bot cross_repo_test manageiq-api#2345, manageiq-ui-classic#3456` would produce:
```diff
-REPOS=ManageIQ/manageiq#1234
+REPOS=ManageIQ/manageiq#1234,ManageIQ/manageiq-api#2345,ManageIQ/manageiq-ui-classic#3456
...
TEST_REPO=ManageIQ/manageiq-api#2345
TEST_REPO=ManageIQ/manageiq-ui-classic#3456
```
---
The "Before" is not accurate because the tests are not running within the entire suite of changes as can be seen in the "After".  Thus, this change no longer puts the onus on the developer to remember to add everything (again) in the including section.
@agrare Please review.

Ensure test_repos that are branches/PRs are part of the repos list

---

.rubocop_local.yml

This data has intentional errors in it so that when the bot runs rubocop
it can pick up real errors (and thus report on them).
Partial fix for #538 (drops the number of offenses in this repo from 121
to 18)

Ignore spec data in rubocop

---

app/models/branch.rb
config/boot.rb
lib/github_service/commands/cross_repo_test.rb
lib/threadsafe_service_mixin.rb
spec/lib/pivotal_service_spec.rb
spec/models/repo_spec.rb

Just a small PR that addresses some linter issues brought up in https://github.com/ManageIQ/miq_bot/issues/538:
* Use Integer instead of Fixnum
* Remove unused variables
* Re-enable a cop when finished
* File.exist? vs File.exists?
* ~~Make private class methods private~~
* Remove unnecessary require

Rubocop fixes

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

For example,
If in PR `Foo/bar#1234`, if someone does, `@miq-bot cross-repo-test #2345`, then it will fail showing a conflict between `Foo/bar#1234` and `Foo/bar#2345`.  Note that a bare PR number will always conflict, so we could change this to fail-fast, but I thought the conflict error message would be much cleaner.

Handle bare PR numbers in cross-repo-test

---

lib/linter/base.rb
lib/linter/haml.rb
vendor/stubs/parser/current.rb

Injects a "stub" 'parser/current' file (that should be appended to the Ruby `$LOADPATH`), which avoids the annoying loading the original, which includes the unskippable warnings like this:
```
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.2-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```
in `STDERR`, which are flagged by the bot as errors (when they aren't useful to the end user).
This stub will just define the `Parser::CurrentRuby` constant manually using the conventions of the `parser` gem.
Example in the wild
-------------------
https://github.com/ManageIQ/manageiq-ui-classic/pull/7650#issuecomment-789178507
(copied in case that goes away)
> Checked commit
> …

[Linter::Haml] Avoid haml-lint STDERR warnings

---

lib/linter/base.rb
spec/lib/linter/base_spec.rb
spec/lib/linter/haml_spec.rb
spec/lib/linter/rubocop_spec.rb

The argument for `env` passed to `Open3.capture3` (or `Open3.capture2e`) needs to be a `Hash`, and not an `Array`, other wise the following error is provided:
```
ArgumentError: wrong first argument
/usr/share/ruby/open3.rb:213:in `spawn'
/usr/share/ruby/open3.rb:213:in `popen_run'
/usr/share/ruby/open3.rb:101:in `popen3'
/usr/share/ruby/open3.rb:281:in `capture3'
/usr/share/gems/gems/awesome_spawn-1.5.0/lib/awesome_spawn.rb:127:in `launch'
/usr/share/gems/gems/awesome_spawn-1.5.0/lib/awesome_spawn.rb:80:in `run'
/opt/miq_bot/lib/linter/base.rb:92:in `run_linter'
/opt/miq_bot/lib/linter/base.rb:27:in `block in run'
/usr/share/ruby/tmpdir.rb:93:in `mktmpdir'
/opt/miq_bot/lib/linter/base.rb:18:in `run'
/opt/miq_bot/app/workers/concerns/code_analysis_mixin.rb:24:in `run_all_linters' …
```

[Linter::Base] Fix invalid .linter_env

---

lib/github_service.rb
lib/github_service/command_dispatcher.rb
lib/github_service/commands/add_label.rb
lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/command_dispatcher_spec.rb
spec/lib/github_service/commands/add_label_spec.rb

Removes bot thinking it is calling itself when making a comment where it's username could be used when adding a label.
See the following for an example:
https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/124#issuecomment-783647447

Fix recursive bot commands

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

When provided with just the following:
```
@miq-bot cross-repo-test
```
Don't blow up when there are no repos available to call `.flat_map` on.
Example stacktrace
------------------
```
I, [2021-08-10T16:27:10.378096 #6]  INFO -- : Executed GET https://api.github.com/orgs/ManageIQ/members/chessbyte...api calls remaining 2321
2021-08-10T16:27:10.379Z 6 TID-gn94tzmqy GithubNotificationMonitorWorker JID-290814c7bffbae7880d9b0ce ERROR: undefined method `flat_map' for nil:NilClass
2021-08-10T16:27:10.380Z 6 TID-gn94tzmqy GithubNotificationMonitorWorker JID-290814c7bffbae7880d9b0ce ERROR: /opt/miq_bot/lib/github_service/commands/cross_repo_test.rb:140:in `parse_value'
/opt/miq_bot/lib/github_service/commands/cross_repo_test.rb:126:in `_execute' …
```

[CrossRepoTest] Handle no input

---

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
spec/support/rubocop_spec_helper.rb
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_offenses/results.json
spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb

Updates COP_URIS so that it also generate correct URLs for cops in `rubocop-rails`, and not just the base gem.
Uses code from the gem to handle generating the URL, and modifies the URL a bit more to properly handle the plugin versions
Links
-----
* https://github.com/rubocop/rubocop/blob/de4f7cdd266999bf2cfbe78bd7fd8a0d4580863d/lib/rubocop/cop/documentation.rb
* https://github.com/rubocop/rubocop/blob/de4f7cdd266999bf2cfbe78bd7fd8a0d4580863d/lib/rubocop/cop/base.rb#L63-L69

[MessageBuilder] Include `rubocop-rails` links

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

There is a limit of 20 on the number of times other workflows can be referenced in a workflow, so rather than 1 job per repo use a matrix for test-repo

Use a matrix for test-repos not jobs

---

lib/github_service/commands/cross_repo_test.rb

```
(byebug) pp github_workflow_yml_content
"---\n" +
"name: Cross Repo Tests\n" +
"on:\n" +
"- pull_request\n" +
"jobs:\n" +
"  cross-repo:\n" +
"    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master\n" +
"    with:\n" +
"      test-repos: '[\"foo\", \"bar\"]'\n" +
"      repos: repo1,repo2\n"
```

Fix YAML replacing on: with true: in github workflow

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

Alternative to fixing https://github.com/ManageIQ/miq_bot/pull/585 is just to support both `" "` and `","` deliminated repo names.  Spaces aren't valid in any of our repo name formats (repo names, PR short format, branch names, urls) so not sure why we explicitly don't allow spaces for separating repo names here.

Support space deliminated repo names for cross-repo-tests

---

lib/github_service/commands/cross_repo_test.rb
spec/lib/github_service/commands/cross_repo_test_spec.rb

@agrare Please review.
This drops the typo spec, which I can't get passing after this change, because there's no way to get a verifiably bad repo name after this point.  Instead it will just create a PR with the "ManageIQ/typo" repo name, which we don't want to handle as per https://github.com/ManageIQ/miq_bot/blob/4e593a7912dbd82740446ce2b6f14caca90fa73c/spec/lib/github_service/commands/cross_repo_test_spec.rb#L329-L336

Add support for the word 'includes' in addition to 'including'

---

lib/github_service/commands/cross_repo_test.rb

Now that we allow spaces as delimiters the command this is no longer a valid check for valid repo names

Drop unnecessary validate_repo_names method

---

app/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker.rb
spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker_spec.rb

A common mistake for developers when updating a branch to include changes from master is to create merge commits like https://github.com/ManageIQ/manageiq-providers-ibm_cloud/commit/da298f3fdf3e9243a89dc2ac62784b16b9f205b6 rather than rebasing their commits on top of the master branch.
We recommend setting `git config pull.rebase true` to avoid this but often times new developers miss this.

Warn users about merge commits in PRs

---

Gemfile
Gemfile.lock

Sidetiq does not work with 5.2.10, possibly because it requires a _much_
newer version of redis.  For now, we will downgrade, but long term we
need to drop sidetiq as it is no longer maintained (See
https://github.com/ManageIQ/miq_bot/issues/282).

Downgrade sidekiq to 5.2.9

---

app/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker.rb
spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker_spec.rb

Change the offense entry severity for a merge commit from :grey_exclamation: to :warning:

Change merge commit severity to :warning:

---

Gemfile
Gemfile.lock
app/workers/batch_job_monitor.rb
app/workers/commit_monitor.rb
app/workers/github_notification_monitor_worker.rb
app/workers/pull_request_monitor.rb
app/workers/schedulers/stale_issue_marker.rb
app/workers/travis_build_killer.rb
config/routes.rb
config/sidecloq.yml

Closes #282
https://github.com/mattyr/sidecloq
@bdunne @agrare Please review.
I need help verifying this because for some reason locally Rugged is having issues with my private keys...it's an unrelated issue, but it prevents me from testing with "real" repos like the sandbox.
Also, switching to Sidecloq should now unlock our Sidekiq version, since we are no longer dependent on celluloid.  I did not do that in this PR, but will do a couple followup PRs to unlock Sidekiq first to 5.2.latest and then to 6

Replace Sidetiq with Sidecloq

---

lib/github_notification_monitor.rb
lib/github_service/notification.rb

@bdunne Please review.  I'm currently seeing the following in production:
```
I, [2023-02-22T18:37:08.761973 #7]  INFO -- : Executed GET https://api.github.com/repos/ManageIQ/manageiq/notifications?all=false&per_page=100...api calls remaining 743
2023-02-22T18:37:08.765Z 7 TID-gok9iyg9n GithubNotificationMonitorWorker JID-839d87e14bc7d073b63b6605 ERROR: undefined method `match' for nil:NilClass
2023-02-22T18:37:08.765Z 7 TID-gok9iyg9n GithubNotificationMonitorWorker JID-839d87e14bc7d073b63b6605 ERROR: /opt/miq_bot/lib/github_service/notification.rb:10:in `issue_number'
/opt/miq_bot/lib/github_notification_monitor.rb:37:in `process_notification'
/opt/miq_bot/lib/github_notification_monitor.rb:26:in `block in process_notifications'
/opt/miq_bot/lib/github_notification_monitor.rb:25:in …
```

Be more resilient on missing notification issue numbers

---

app/workers/stale_issue_marker.rb
spec/workers/stale_issue_marker_spec.rb

lets drop the auto close feature for stale PRs
I was not able to run tests locally, so this is more of a conversation starter.

Drop close issue

---

container-assets/entrypoint
templates/bot.yaml

- Sync up deployments from the running bot
- Change the settings location to come from a secret now that the defaults are checked in and only secret values are stored in the yml

Update deployment logic for settings changes

---

container-assets/entrypoint
templates/bot.yaml

Also:
- drop readiness delay (the containers don't take long to boot)
- drop timeoutSeconds since it's the default

Precompile assets in production

---

lib/tasks/production.rake

Update production cluster

---

lib/tasks/production.rake

@bdunne Please review.  I verified this as I released v0.20.4 and it did what was expected. Technically this also fixes a bug where the docker build looked at the tip of the branch instead of the tag.

Add a check that the release version matches the deployment yml

---

config/settings/production.yml

- Add dependencies rule to more repos
- Remove path based labeler rules for embedded ansible and sql migration

Update production settings

---

lib/tasks/production.rake

Add production.rake helpers for IbmCloud

---

.github/workflows/build_and_deploy.yml
lib/tasks/production.rake

Add GitHub Action to build and deploy

---

lib/github_notification_monitor.rb
spec/lib/github_notification_monitor_spec.rb

2024-06-20T15:15:07.763Z pid=7 tid=e53 class=GithubNotificationMonitorWorker jid=cfc7e8ea0ca87af4aac174f2 ERROR: Tried to load unspecified class: Date
2024-06-20T15:15:07.763Z pid=7 tid=e53 class=GithubNotificationMonitorWorker jid=cfc7e8ea0ca87af4aac174f2 ERROR: /usr/share/gems/gems/psych-4.0.4/lib/psych/class_loader.rb:99:in `find'

Allow loading YAML loading Dates

---

Gemfile
Gemfile.lock

```
sh-5.1# bundle exec rails c
/usr/share/gems/gems/railties-6.1.7.8/lib/rails/commands/console/console_command.rb:3:in `require': cannot load such file -- irb (LoadError) Did you mean?  erb
drb
from /usr/share/gems/gems/railties-6.1.7.8/lib/rails/commands/console/console_command.rb:3:in `<top (required)>'
from /usr/share/gems/gems/railties-6.1.7.8/lib/rails/command/behavior.rb:44:in `require'
from /usr/share/gems/gems/railties-6.1.7.8/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
from /usr/share/gems/gems/railties-6.1.7.8/lib/rails/command/behavior.rb:40:in `each'
from /usr/share/gems/gems/railties-6.1.7.8/lib/rails/command/behavior.rb:40:in `block in lookup'
from /usr/share/gems/gems/railties-6.1.7.8/lib/rails/command/behavior.rb:39:in `each'
from …
```

Add irb for rails console

---

Gemfile
Gemfile.lock

Pin concurrent-ruby to < 1.3.5 for Rails 6.1 support

---

db/migrate/20250305205548_add_uniqueness_constraint_on_branches.rb
db/schema.rb
spec/models/branch_spec.rb

Somehow we have duplicate (2-3) branch records being created at the same time (within 1 second) in the prod database and the rails validation is not good enough.  Let the database handle the uniqueness to prevent this from happening in the future.

Add database level uniqueness on branch records

---

Dockerfile
config/application.rb
spec/miq_bot_spec.rb

@bdunne Please review. In prod, since we pull the tarball, there is no git dir, and thus no version output. This creates a VERSION file instead, which can be used to display the current version in prod.

Add support for a VERSION file

---

lib/tasks/production.rake

@bdunne Please review.  I accidentally did the wrong thing, passing the remote first in the parameters, and it went ahead and created a vupstream tag and "release".  This prevents that kind of mistake moving forward.

Check version format during release

---

Dockerfile

The CentOS Stream packages conflict with openssl-fips-provider from UBI

Don't include newer openssl packages from CentOS Stream

---

Dockerfile

Error:
```
Error: 
Problem 1: package rpm-libs-4.16.1.3-38.el9.x86_64 from baseos requires libcrypto.so.3(OPENSSL_3.4.0)(64bit), but none of the providers can be installed
- cannot install the best update candidate for package rpm-libs-4.16.1.3-37.el9.x86_64
- package openssl-libs-1:3.5.0-1.el9.x86_64 from baseos is filtered out by exclude filtering
- package openssl-libs-1:3.5.0-2.el9.x86_64 from baseos is filtered out by exclude filtering
- package openssl-libs-1:3.5.0-3.el9.x86_64 from baseos is filtered out by exclude filtering
Problem 2: package python3-rpm-4.16.1.3-38.el9.x86_64 from baseos requires rpm-libs(x86-64) = 4.16.1.3-38.el9, but none of the providers can be installed
- package rpm-libs-4.16.1.3-38.el9.x86_64 from baseos requires libcrypto.so.3(OPENSSL_3.4.0)(64bit), but …
```

Switch to newer openssl for rpm, ruby and nodejs from CentOS Stream
