Gemfile, Gemfile.lock, app/models/commit_monitor_repo.rb, app/workers/travis_build_killer.rb
=> Add TravisBuildKiller which kills dup builds for the same PR/branch.

lib/bot/issue_manager.rb
Also add logging of the command that is being run.
=> Fix issue manager command checker to account for whitespace.

app/workers/commit_monitor_handlers/commit/gemfile_checker.rb, app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
Depends on https://github.com/ManageIQ/miq_tools_services/pull/7
=> Extract replacing github messages into miq_tools_services.

app/workers/commit_monitor_handlers/commit/gemfile_checker.rb
@jrafanie Please review.
Depends on https://github.com/ManageIQ/miq_tools_services/pull/8
=> Extract label management to miq_tools_services

app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb
Previously, we were doing haml linting on ruby files.  ¯\_(ツ)_/¯
cc @brandondunne @Fryguy
=> We need to whitelist the ruby/haml linter file lists separately.

README.md
This adds the steps required to get up and running in development.
=> Add developer setup

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb, spec/support/rubocop_spec_helper.rb, spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb
=> Added haml-lint with version to the commit monitor message

Gemfile, Gemfile.lock, app/models/commit_monitor_repo.rb, app/workers/pull_request_monitor.rb, app/workers/pull_request_monitor/pr_branch_record.rb, app/workers/pull_request_monitor/repo_processor.rb, spec/factories/branch.rb, spec/factories/repo.rb, spec/models/commit_monitor_repo_spec.rb, spec/spec_helper.rb, spec/workers/pull_request_monitor/pr_branch_record_spec.rb, spec/workers/pull_request_monitor/repo_processor_spec.rb
* Pulls the worker logic out of private methods and into public methods on the repo model and stateless services so that it can be more easily tested. 
* Adds specs for all the above
* Adds factory girl to aid in model tests
=> Refactor iceberg class pull request monitor

README.md
First two args have been merged, so this updates the README accordingly.
=> Update README for `Repo.create_from_github!`

spec/models/batch_job_spec.rb
=> Fix expires_at test

app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/migration_date_checker.rb, spec/workers/commit_monitor_handlers/batch/github_pr_commenter/migration_date_checker.rb
Resolves #113 
@jrafanie Please review.
=> Add checker for bad migration timestamps

app/workers/commit_monitor.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/gemfile_checker.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/migration_date_checker.rb, app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb, app/workers/concerns/branch_worker_mixin.rb, spec/workers/commit_monitor_handlers/batch/github_pr_commenter/gemfile_checker_spec.rb, spec/workers/commit_monitor_handlers/batch/github_pr_commenter/migration_date_checker_spec.rb
NOTE: "master" has been hardcoded.  I plan to move this into a new column Branch#destination_branch (or thereabouts) in a future PR
Depends on https://github.com/ManageIQ/miq_tools_services/pull/14
@bdunne Please review
=> Change diff-based workers to determine based on a merge into master.

app/workers/travis_build_killer.rb
Fixes #52 
@jrafanie @bdunne Please review
@matthewd This should fix the issue with capablanca.
=> Fix issue where TravisBuildKiller grouped all non-PRs together.

app/models/batch_entry.rb, spec/models/batch_entry_spec.rb
=> Fix race condition where the BatchJob could be destroyed externally

app/workers/travis_build_killer.rb
Sometimes Travis builds get stuck and Travis doesn't kill them.  This can result in builds running for 18+ hours before someone notices and manually kills them.  Since that worker was tied up, the Travis backlog continues to grow.
=> Kill Travis builds that are running for over 1 hour

app/workers/issue_manager_worker.rb
Fixes an issue we saw where an issue manager worker started while
another was running.
=> Run the issue manager worker if there isn't already one :open_mouth:

Gemfile, Gemfile.lock, db/schema.rb
* Upgrade sidekiq to 3.5.3 and celluloid to 0.17.2 
* Use a fork of sidetiq to support celluloid 0.17+: tobiassvn/sidetiq#142
* Update more_core_extensions to remove Object#namespace monkey patch
=> Upgrade sidekiq

.travis.yml, Procfile.tmpl, app/workers/commit_monitor.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/gemfile_checker.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/migration_date_checker.rb, app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb, app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb, app/workers/pull_request_monitor.rb, app/workers/travis_event_handlers/stalled_finished_job.rb
=> Create a slow queue for tasks that require locking on git or Github

Gemfile, Gemfile.lock
4.0 no longer depends on celluloid.  Hope to remove extra celluloid threads.
=> Upgrade to Sidekiq 4.0.1

Gemfile, Gemfile.lock, app/models/repo.rb, app/workers/commit_monitor.rb, app/workers/pull_request_monitor/pr_branch_record.rb, db/migrate/20151204171252_update_branch_name_for_pr_branches.rb, spec/factories/branch.rb, spec/support/miq_tools_services_helper.rb, spec/workers/pull_request_monitor/pr_branch_record_spec.rb, spec/workers/pull_request_monitor/repo_processor_spec.rb
Requires changes in https://github.com/ManageIQ/miq_tools_services/pull/19
- Don't create extra branches
- Use the new fetched PRs 
- Migrate PR Branches to use the new name
=> Fetching prs

db/migrate/20151204171252_update_branch_name_for_pr_branches.rb
=> fix migration of branch name

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
=> :trophy: in message_builder

app/models/branch.rb, app/models/repo.rb, app/workers/pull_request_monitor.rb, app/workers/pull_request_monitor/pr_branch_record.rb, app/workers/pull_request_monitor/repo_processor.rb, spec/workers/pull_request_monitor/pr_branch_record_spec.rb, spec/workers/pull_request_monitor/repo_processor_spec.rb
Based on changes in https://github.com/ManageIQ/miq_bot/pull/145
=> Prevent pull request monitor from blocking on git

app/models/repo.rb, app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb, lib/linter/rubocop.rb
I ran into a few issues while updating the bot code
=> Fixes while updating

lib/linter/rubocop.rb
Output from a test run against https://github.com/ManageIQ/manageiq/pull/7212.....
```
Linter::Rubocop Branch prs/7212/head - Starting Rubocop run...
Linter::Rubocop Branch prs/7212/head - Collected files ["/tmp/d20160318-12944-1im7qeu/rubocop/spec", "/tmp/d20160318-12944-1im7qeu/rubocop/spec/models", "/tmp/d20160318-12944-1im7qeu/rubocop/spec/models/miq_replication_worker", "/tmp/d20160318-12944-1im7qeu/rubocop/spec/models/miq_replication_worker/runner_spec.rb", "/tmp/d20160318-12944-1im7qeu/rubocop/app", "/tmp/d20160318-12944-1im7qeu/rubocop/app/models", "/tmp/d20160318-12944-1im7qeu/rubocop/app/models/miq_worker", "/tmp/d20160318-12944-1im7qeu/rubocop/app/models/miq_worker/runner.rb", "/tmp/d20160318-12944-1im7qeu/rubocop/app/models/miq_replication_worker", …
```
=> Add logging to Linter::Rubocop to help troubleshoot failures

lib/linter/rubocop.rb
Fixes `Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8`
=> Fix encoding issues when writing out blobs.

config/environments/production.rb, config/environments/test.rb
`serve_static_assets` has been deprecated.
=> Use `config.serve_static_files`

app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb, lib/linter/base.rb, lib/linter/haml.rb, lib/linter/rubocop.rb
Move Haml linter to a module like rubocop
=> Haml linter

Gemfile, Gemfile.lock
The branch we were previously pointing to has been merged:
https://github.com/tobiassvn/sidetiq/commit/dca88dd5841e2b1336fbfdbdcbe9e9437947369b
=> Upgrade to sidetiq 0.6.1

app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb, lib/git_service/branch.rb
Command line merging is painfully slow and the volume is becoming a problem
=> Use rugged to determine branch mergeability

app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb, config/settings.yml
- Accidentally deleted method
- default value in settings.yml
=> Diff content checker followup

Gemfile
Removes warning on bundle install
=> Use HTTPS in git-based gems

app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb, app/workers/commit_monitor_handlers/branch/pr_mergeability_checker.rb
=> Fix tags that are no longer hidden on GitHub

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb, lib/linter/base.rb
- Make line location optional
- Write an error message when linter config files are missing
- Write an error message when JSON parsing fails
- Skip the linter when there are no files to be linted
=> Linter problems

app/models/repo.rb
I was hitting issues locally with SSH based repos, and so I dug deeper and found that Rugged doesn't look at the sshagent by default.  Somehow it's working on our Linux server, but on my Mac it totally fails.  This should handle all cases.
Note that I wanted top use URI.parse, but the `git@github.com:miq-test/sandbox` URL is not a valid URL and it won't parse, so I resorted to using a Regex.
=> Fix issue where git remotes would not fetch correctly

app/helpers/application_helper.rb, app/views/layouts/_navbar.html.erb, lib/miq_bot.rb
This PR helps answer the question "What is currently deployed?"
=> Add application version to UI

app/workers/commit_monitor_handlers/commit_range/gem_changes_labeler.rb, spec/workers/commit_monitor_handlers/commit_range/gem_changes_labeler_spec.rb
@bdunne Please review.  Once released I'd like to start monitor the major repos for this.
cc @skateman @himdel
=> Add support for checking gemspecs as well as Gemfiles

app/workers/commit_monitor_handlers/commit/pivotal_pr_checker.rb
=> Fix issue where text from Pivotal could be nil

app/models/git_hub_api.rb, lib/github_service.rb, lib/github_service/logging_patch.rb
@bdunne @chrisarcand Please review
=> Fix ratelimit logging

config/initializers/services_initializer.rb
~~Depends on https://github.com/ManageIQ/miq_tools_services/pull/24~~ Obviated by #265 
@bdunne @chrisarcand Please review
=> Add support for Github rate limit logging

app/models/branch.rb, spec/models/branch_spec.rb
@chrisarcand Please review.  This should fix the [DARGA][DARGA] issue.
=> Fix issue where existing title tags may not have space delimiters.

Gemfile
minigit somehow got duplicated in the Gemfile
=> Remove minigit duplicate from Gemfile

app/models/batch_job.rb
It's deprecated in Ruby 2.3 (we aren't running 2.3 yet, but I was locally and noticed this)
=> Remove deprecated Thread.exclusive

app/workers/batch_job_monitor.rb, app/workers/commit_monitor.rb, app/workers/github_notification_monitor_worker.rb, app/workers/pull_request_monitor.rb, app/workers/travis_build_killer.rb
@chrisarcand Please review.  This is 1 of a number of small PRs I'm going to make to cleanup various things that came from the enable/disable work.
=> Cleanup includes for consistency

app/models/batch_entry.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_filename_checker.rb, app/workers/concerns/batch_entry_worker_mixin.rb, app/workers/concerns/batch_job_worker_mixin.rb, spec/models/batch_entry_spec.rb
@chrisarcand Please review.
This adds skipping batch entries, which is important for enable/disable effort.
=> Add ability to skip batch entries.

config/settings.yml, lib/bugzilla_service.rb, lib/bugzilla_worker_common.rb, lib/github_usage_tracker.rb
@chrisarcand This is part 2 of the cleanup.  Minor rearrangement of the settings, and also rebucketing some bugzilla specific settings.
=> Rearrange settings

app/workers/travis_build_killer.rb
=> Extract method refactoring in TravisBuildKiller

lib/github_notification_monitor.rb, lib/github_service.rb, lib/github_service/issue.rb, spec/models/github_notification_monitor_spec.rb
I broke all these methods in previous commits.
Copy pasta.
Oops.
=> Fix caching methods

lib/github_notification_monitor.rb, lib/github_service.rb, lib/github_service/issue.rb
=> Fix labeling and WIP titler

lib/github_service.rb, lib/github_service/issue.rb
This does a few things:
* `remove_labels` is no longer supported, because the API does not support
multiple label removal. The trick around that before was to replace all
the labels on the issue instead of removing one by one, but that causes
a new 'label adding event' in the UI even as it's replacing. Lame.
Forunately we weren't using the plural form anywhere yet anyway.
* Consolidates all of the logic of "Don't add a label to an issue if
that issue already has the label" all in one spot, and funnels ALL
calls (through the Issue wrapper OR the GithubService call) through
the same interface. The Issue class has the logic because if you put
it in the overrided method in GithubService, you'd paying a tax in
refetching the issue if the Issue object is trying to add a label to
itself.
* Adds …
=> Safer labeling

lib/github_service/issue.rb
The previous solution didn't accept hyphens.
=> Fix regex in Issue wrapper

app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb, spec/workers/commit_monitor_handlers/commit_range/path_based_labeler_spec.rb
@chrisarcand Fixed this.  Please review.
=> Move PathBasedLabeler to be a commit_range handler

lib/github_usage_tracker.rb, spec/lib/github_usage_tracker_spec.rb
@chrisarcand Please review.  I did not have influx configured locally, and GitHub calls were hanging indefinitely for me.
=> Make influxdb actually optional

app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_content_checker.rb, app/workers/commit_monitor_handlers/batch/github_pr_commenter/diff_filename_checker.rb, app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb, lib/git_service/branch.rb, lib/git_service/error.rb
@chrisarcand Please review
cc @bdunne
=> Create a proper GitService::UnmergeableError

app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb, spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb
http://manageiq.org/blog/2016/11/announce_f_name/
=> It's time to tell us how fine our PRs are.

Gemfile
Removed a couple of offending Rubocop lines, as they were not using
hashrockets.
=> The mighty hashrocket has spoken. They shall not forget me.

README.md, spec/lib/linter/yaml_spec.rb
* updates a spec to give it a more useful description (d'oh)
* updates the README with details of the new prerequisites/packages
@miq-bot assign @Fryguy
=> Post yamllint updates

app/models/branch.rb, app/models/repo.rb, lib/git_service/branch.rb, spec/models/repo_spec.rb
Given a name, it will check the git repo on the filesystem, and if the branch exists, fill in the details and create a Branch record
=> Add Repo#create_branch method

app/workers/concerns/code_analysis_mixin.rb, spec/workers/concerns/code_analysis_mixin_spec.rb
Simplify building the resulting hash and verify that it always has the expected keys
=> Add a basic tests for CodeAnalysisMixin#merged_linter_results

lib/linter/yaml.rb, spec/lib/linter/yaml_spec.rb
Tested in production, appears to fix the issue
=> Yaml linter error

README.md
=> Document enabling and disabling workers

lib/bugzilla_service.rb, spec/lib/bugzilla_service_spec.rb, spec/lib/minigit_service_spec.rb, spec/support/settings_helper.rb
Additionally changes the URL to be based off that which is configured in
the Settings.
Closes #353 
=> Add support for alternate bugzilla URLs

app/workers/code_analyzer.rb, app/workers/schedulers/code_analyzer.rb
=> Move CodeAnalyzer to only run nightly and not per merge

lib/linter/base.rb
For regular branches, continue writing to the log and requeueing for now.  For PR's, write the errors to the PR message.  It should help us troubleshoot linting errors quicker and without the need to access the bot machine directly.
=> Write linter errors to the pull request

lib/linter/base.rb
=> Add another newline to fix the markdown syntax

spec/lib/bugzilla_service_spec.rb
=> Update cop namespace and re-enable cop at the end of the file

spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/diff_content_checker_spec.rb
This is less of a "new feature" and more of a way we should consider handling checking for `puts` in our `config/settings.yml`.
In the current config by just looking for `puts` as a "word", we will end up flagging it when it is in comments or just in an everyday sentence (you know... since it is a 'word' in the English dictionary).
The suggestion I am proposing basically is to make the `puts` check a regexp that will not match against any line that includes a `#` proceeding the word, and I re-worked the specs to show how that would work.
* * *
The alternative to this approach would be to add the following regexp matcher preamble:
```ruby
/^([^#]+|)\b#{my_bad_word}\b/
```
To the "word" `Regexp` for of the content checker.  I figured this was more invasive so I went with the above, but …
=> Add (suggestion for) better regexp for puts

.travis.yml, Gemfile.lock
- Bump Travis Ruby version to 2.5.5
- Set up PostgreSQL properly
=> Fix Travis issues

app/models/repo.rb, spec/models/repo_spec.rb
When repos move I have to do a lot of this clone management manually and it's very error prone (e.g. recently the catalog, topo, etc moves).  These methods will prevent that.  Eventually we can probably detect repo name changes and do these moves automatically, but this is just a crawl phase.
=> Ensure clone is moved or destroyed on Repo#name changes

Gemfile.lock, app/models/repo.rb, systemd/miq_bot-sidekiq.service, systemd/miq_bot-sidekiq_glacial.service, systemd/miq_bot-thin.service
- Upgrade rugged
- rescue failures trying to delete directories that don't exist
- switch back to fetching using minigit
- add new systemd scripts
=> Apply changes from the production box

systemd/miq_bot-sidekiq.service, systemd/miq_bot-sidekiq_glacial.service, systemd/miq_bot-thin.service, systemd/miq_bot.service
This allows us to stop and start all of the services in a single shot.
@bdunne @agrare Please review.
Note that I did not test this... @bdunne I'm gonna need your help with that.
=> Add top-level systemd unit to group all miq_bot services

lib/linter/haml.rb, lib/linter/rubocop.rb
=> Include rubocop config files during haml-lint

Gemfile, Gemfile.lock, config/environments/production.rb
Resolves issue in https://github.com/ManageIQ/miq_bot/pull/495#issuecomment-642932691
Based on discussion with @Fryguy and @himdel starting around [June 15, 2020 4:38 PM](https://gitter.im/ManageIQ/miq_bot?at=5ee7dc2c5782a31278ffb6b6)
=> Remove uglifier and coffee-rails since they aren't used

Dockerfile, container-assets/container_env, container-assets/entrypoint, templates/bot.yaml
- Add a Dockerfile and supporting entrypoint script
- Add templates for the application and supporting services, minus ConfigMaps, Secrets and PVCs
=> Initial Podification effort

.gitignore, README.md, lib/github_service/commands/cross_repo_test.rb, spec/lib/github_service/commands/cross_repo_test_spec.rb, spec/support/git_repo_helper.rb
Addresses https://github.com/ManageIQ/miq_bot/issues/446
Still needs some cleanup, but should handle
- Cloning a configured `*-cross_repo-tests` repo
- Parses args from the command using variations outlined in https://github.com/ManageIQ/miq_bot/issues/446
- Creating a new commit with the `.travis.yml` changes
- Pushes commit and opens a pull request
Uses ideas from the following PRs/branches (thanks to @d-m-u and @Fryguy ):
- https://github.com/ManageIQ/miq_bot/pull/446
- https://github.com/ManageIQ/miq_bot/pull/447
- https://github.com/Fryguy/miq_bot/commit/dc0cc52ca6bbbfeaf5061c6681f4e6c53b9e85ab#diff-b351efdefa95964e43ea7fcabca89843
Notes
-----
- Decent amount of test helpers added to facilitate testing this as much as possible
- Under the assumption we won't be "monitoring" this repo …
=> Add cross_repo_test bot command

app/models/branch.rb
When we branch from master, we need to create branch records for each of those git branches.  This makes it simpler to do so in bulk.
i.e. `Branch.create_all_from_master("kasparov")`
=> Simplify creating the branch records

lib/github_service/commands/cross_repo_test.rb, spec/lib/github_service/commands/cross_repo_test_spec.rb
=> Add the PR identifier to the list of test repos

lib/threadsafe_service_mixin.rb
we don't need to do this and i need a commit for the day
=> don't require threads

lib/github_service/commands/cross_repo_test.rb, spec/lib/github_service/commands/cross_repo_test_spec.rb
This handles the case where someone asks for the same repo multiple times,
but where one is a PR and the other is the bare repo.  This can even happen
accidentally, such as in the following case:
In ManageIQ/manageiq PR 1234, someone asks the bot to process /all, but
/all includes ManageIQ/manageiq.  The bot adds the PR to the test repo
list and now you have both the PR and the bare repo.  Additionally, it
will add the PR to the included list. manageiq-cross-repo will then see
that as an invalid combination because you can't test a bare repo while
also saying that it should include a PR version of that same repo.
This commit will prioritize PRs over bare repos when duplicates are
detected.
@agrare Please review.
=> Handle duplicate repo name where one is a PR and the other is bare

lib/github_service/commands/cross_repo_test.rb, spec/lib/github_service/commands/cross_repo_test_spec.rb
Follow up to #544 
@agrare Please review.
=> Validate invalid repo names and repo name conflicts

lib/github_service/commands/cross_repo_test.rb, spec/lib/github_service/commands/cross_repo_test_spec.rb
=> Add support for PR URLs in cross-repo-tests

lib/tasks/production.rake
- `production:edit_settings` to modify the bot settings in production
- `production:console` to open a console in production
- `release` to tag, build, and release a new version into production
Note that I released a 0.13.7 with the bot using this
=> Add production rake tasks

Dockerfile
This is required by mimemagic dependency
=> Add shared-mime-info to Dockerfile

lib/tasks/production.rake
=> Add ability to console into a specific production deployment

lib/tasks/production.rake
- Add rake task production:logs
- Add rake task production:restart 
=> More production tasks

lib/github_service/commands/cross_repo_test.rb, spec/lib/github_service/commands/cross_repo_test_spec.rb
=> Update miq_bot for cross-repo-tests github actions

Dockerfile
=> Clean up more things for a smaller image size

Dockerfile, Gemfile.lock
Based on https://github.com/ManageIQ/manageiq/pull/22007
=> Build rugged with SSH support

Gemfile.lock
=> Bump manageiq-style to 1.3.3

app/workers/stale_issue_marker.rb, config/settings.yml
In the prod config I'll add the other labels.
=> Add configurable pinned labels for StaleIssueMarker

app/workers/stale_issue_marker.rb
- Remove the comment footer because it just makes the comments large with little benefit.
- Remove the ununsed methods
- Make the query methods return fragments without the leading space.
- Small rubocop fixes
@kbrock Please review.
=> Various cleanup in the stale issue marker

config/settings/production.yml
=> Add production settings

config/settings/production.yml
@bdunne Please review.  I missed hitting Save on these in #664
=> Cleanup some production settings

Gemfile
=> Add bundle_inject

lib/tasks/foreman.rake
=> Drop foreman:export rake task

container-assets/container_env
=> Set defaults in container_env for dev usage

app/models/branch.rb, spec/models/branch_spec.rb
=> Fix issue where tags with dashes are ignored

Dockerfile
Related: https://github.com/ManageIQ/manageiq-rpm_build/pull/467
Switch to my patched RPM to use CentOS Vault
=> CentOS Stream 8 is EOL

.github/workflows/build_and_deploy.yml, .github/workflows/ci.yaml, Dockerfile, Gemfile, Gemfile.lock, app/workers/stale_issue_marker.rb, lib/git_service/repo.rb, lib/github_notification_monitor.rb, lib/github_service/commands/cross_repo_test.rb, spec/lib/github_notification_monitor_spec.rb
TODO:
- UI works
- Sidekiq works
- Sidetiq works
- Notification Monitor works (responds appropriately to good and bad commands) 
- WIP labeler works
=> Upgrade Dockerfile to UBI9

Dockerfile
- Fix libcurl openssl-libs conflict
- Add missing yaml.h for psych
=> Fix builds

lib/tasks/production.rake
@bdunne Please review - I used this to release the most recent version.
=> Auto update the version number in bot.yaml on release

Dockerfile
=> Fix docker build by removing the openssl-libs override

Gemfile.lock
=> Bump nokogiri to 1.18.2

config/settings/production.yml
=> Add spassky labels

config/settings/production.yml
=> Add terraform enterprise plugin

README.md
I tend to forget the difference between the including section or test_repos section
=> describe cross repo test usage

config/settings/production.yml
=> Add Nutanix provider to core repos
